### PR TITLE
Added the hover effects in the nav bar

### LINKED ISSUE #27: feat: hover effects in the navbar
### Description

The footers and other icons have a hover effect, except the navbar I want to add the hover effect to increase the interactiveness of the website.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by mnik7044**
Closes #27 

## 🛠️ Fixes Issue

 Added the hover effect in the main as well as services page of the website. 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Video 

https://user-images.githubusercontent.com/108953684/231884955-f497b9f6-e119-4038-8857-f1f5d80b77f8.mp4

### CODE REVIEW

**Comment by mnik7044** [comment]
Hey @Pradumnasaraf I have added the hover effects please review it.

**Comment by Pradumnasaraf** [comment]
Hey, there is a nav bar code inside the bundle as well. Add a hover effect to that as well.

Also, add a delay same as the footer one.

**Comment by mnik7044** [comment]
Hey @Pradumnasaraf I have added the hover effect to the CSS of the bundle folder and also added the transition in all the three CSS files please review the changes

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution

**Comment by mnik7044** [comment]
Thank you for the opportunity @Pradumnasaraf a lot to learn from you!

**Pull request merged**
