### PR TITLE
feat: Made Site responsive for mobile screens

### LINKED ISSUE #3: [FEATURE] Make it responsive
### Description

Right now it only works properly on Pc

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by shriekdj**
## 🛠️ Fixes Issue

Closes #3 

## 👨‍💻 Changes proposed

- Made `Top` class Responsive
- Made `heading` and `left` class responsive
- Made `right` class responsive
- Site is ready to View on Mobile Screens.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Only Stylesheet is updated

## 📷 Screenshots
Screenshot_2022_0302_031012

### CODE REVIEW

**Comment by shriekdj** [comment]
the given screenshot is long screenshot my mobile screen is not that long 😊

**Comment by shriekdj** [comment]
tag me if any correction needed

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
**Hey! Thank you for your contributions to this project, everything is working great.**

Just need some changes, can you please add some margin around the social media elements?
Screenshot from 2022-03-02 10-33-30

**Comment by shriekdj** [comment]
ok changes done

**Review by Pradumnasaraf — APPROVED** [review]
LGTM! Thank you for your contribution

**Comment by KendallDoesCodingAlt1** [comment]
Noice.

**Pull request merged**
